### ISSUE TITLE
[Bug]: AllowList assuming role not working as expected

### ISSUE THREAD

**Issue by toniblyx** [toniblyx/prowler#1630]
### Discussed in https://github.com/prowler-cloud/prowler/discussions/1628

<div type='discussions-op-text'>

<sup>Originally posted by **am-avios** December 29, 2022</sup>
Hi

I configured the allowlist.yaml as 

```yaml
Allowlist:
Accounts:
  "*":
  Checks:
    "sns_topics_kms_encryption_at_rest_enabled":
    Regions:
      - "eu-west-1"
    Resources:
      - "aws-controltower"
```

and scanned an account with prowler 
`# prowler aws -p <> -R <> --region eu-west-1 -b -c sns_topics_kms_encryption_at_rest_enabled --allowlist-file allowlist.yaml`

This still returned failed findings with resources name containing string 'aws-controltower'.

Can anyone point out what i am missing? </div>

**Comment by n4ch04** [comment]
Hi @am-avios we have been testing the allowlist and we can't reproduce the behaviour you mention, for example:

Test case 1 -> only one region is included in allowlist 
`allowlist.yaml` file
```
Accounts:
     "*":
      Checks:
        "sns_topics_kms_encryption_at_rest_enabled":
          Regions:
            - "eu-west-1"
          Resources:
            - "aws-controltower"
 ```
Command executed:

`prowler  -c sns_topics_kms_encryption_at_rest_enabled -R arn:aws:iam::XXXXXXXXX:role/XXXXXX --verbose --allowlist-file allowlist.yaml`

Output:

```
Check ID: sns_topics_kms_encryption_at_rest_enabled - sns [high]
        WARNING eu-west-1: SNS topic arn:aws:sns:eu-west-1:XXXXXXXXX:aws-controltower-XXXXXX is not encrypted
        FAIL us-east-1: SNS topic arn:aws:sns:us-east-1:XXXXXXXXX:aws-controltower-XXXXXX is not encrypted
        FAIL us-east-2: SNS topic arn:aws:sns:us-east-2:XXXXXXXXX:aws-controltower-XXXXXX is not encrypted
        FAIL us-west-2: SNS topic arn:aws:sns:us-west-2:XXXXXXXXX:aws-controltower-XXXXXXX is not encrypted
```
Test case 2 -> all the regions are included in the allowlist

`allowlist.yaml` file
```
Accounts:
     "*":
      Checks:
        "sns_topics_kms_encryption_at_rest_enabled":
          Regions:
            - "*"
          Resources:
            - "aws-controltower"
 ```
Command executed:

`prowler  -c sns_topics_kms_encryption_at_rest_enabled -R arn:aws:iam::XXXXXXXXX:role/XXXXXX --verbose --allowlist-file allowlist.yaml`

Output:

```
Check ID: sns_topics_kms_encryption_at_rest_enabled - sns [high]
        WARNING eu-west-1: SNS topic arn:aws:sns:eu-west-1:XXXXXXXXX:aws-controltower-XXXXXX is not encrypted
        WARNING us-east-1: SNS topic arn:aws:sns:us-east-1:XXXXXXXXX:aws-controltower-XXXXXX is not encrypted
        WARNING us-east-2: SNS topic arn:aws:sns:us-east-2:XXXXXXXXX:aws-controltower-XXXXXX is not encrypted
        WARNING us-west-2: SNS topic arn:aws:sns:us-west-2:XXXXXXXXX:aws-controltower-XXXXXXX is not encrypted
```

Can you check if the results not filtered by the allowlist does not belong to the `eu-west-1` region? In that case you'll need to include those regions in the allowlist file as well.
