### ISSUE TITLE
Add description in allowlist file

### ISSUE THREAD

**Issue by ichasco-heytrade** [toniblyx/prowler#1794]
It would be nice to be able to add some descriptions or notes in `allowlist` file to see them in the report after.

Example:
```
      "s3_bucket_server_access_logging_enabled":
          Regions:
            - "eu-west-1"
          Resources:
            - "s3-logs"
           Description: "This is a S3 log bucket"
```
