### ISSUE TITLE
Additional filter by tags in Allowlist

### ISSUE THREAD

**Issue by dabo-devconsole** [toniblyx/prowler#2103]
### New feature motivation

Allowing resources by name, is sometimes not enough. I want to be able to filter for certain tags on these resources. 

### Solution Proposed

```yaml
Allowlist:
  Accounts:
    "*":
    Checks:
        "s3_bucket_level_public_access_block":
        Regions:
            - "*"
        Resources:
            - "public-resource"  
        Tags:
            - "access=public"
```
### Describe alternatives you've considered

Alternatively it would be nice, to have an option to exclude resources with certain tags.
e.g. "--exclude-tags"
