### ISSUE TITLE
[Bug]: allowlist with tags unexpected behavior

### ISSUE THREAD

**Issue by D592** [toniblyx/prowler#2391]
### Steps to Reproduce

I'm trying to use allowlist.yaml file for reducing false positive - for instance:
```
Allowlist:
  Accounts:
    "*":
      Checks:
        "s3_bucket_default_encryption":
          Regions: ["*"]
          Resources: ["*"]
          Tags:
            - "mytag:env=ppe|mytag:env=demo|mytag:env=staging"
```
It's according documentation ignores all resources with tag  mytag:env=ppe OR mytag:env=demo OR mytag:env=staging
But noting happens and the findings for the resources are marked "FAIL"
The allowlist.yaml file with the next settings - works:
```
Allowlist:
  Accounts:
    "*":
      Checks:
        "s3_bucket_default_encryption":
          Regions: ["*"]
          Resources: ["*"]
          Tags:
            - "mytag:env=ppe"
```
Resources with tag mytag:env=ppe are marked "WARNING"

### Expected behavior

The "allowlist" settings should mark all the findings ("s3_bucket_default_encryption") for the tagged resources  as "WARNING"
```
      Checks:
        "s3_bucket_default_encryption":
          Regions: ["*"]
          Resources: ["*"]
          Tags:
            - "mytag:env=ppe|mytag:env=demo|mytag:env=staging"
```
resourceA with tag mytag:env=ppe, resourceA with tag mytag:env=demo - and so on ... Anyway that behavior is claimed in documentation https://docs.prowler.cloud/en/latest/tutorials/allowlist/

### Actual Result with Screenshots or Logs

prowler aws -M csv html json  -w allowlist.yaml  --checks s3_bucket_default_encryption

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

workstation

### OS used

Ubuntu 22

### Prowler version

Prowler 3.4.1

### Pip version

pip 22.0.2
