### ISSUE TITLE
[Bug]: Allowlist Resources regex not working as documented

### ISSUE THREAD

**Issue by ckdake** [toniblyx/prowler#2465]
### Steps to Reproduce

Allowlist with:
```yaml
Allowlist:
  Accounts:
    "*":
      Checks:
        "iam_policy_allows_privilege_escalation":
          Regions:
            - "*":
          Resources:
            - "run-[[:alnum:]-]+-task"
```

Run prowler against an AWS account that has a task named "run-some-task" that has permissions to `sts:AssumeRole`.

### Expected behavior

Prowler should find the role, see that it fails the check `iam_policy_allows_privilege_escalation`, but because it's in the AllowList via matching the regex it sets the status to "WARNING".

### Actual Result with Screenshots or Logs

Prowler finds the role, sees that it fails the check `iam_policy_allows_privilege_escalation`, and marks it as "FAIL" seeming to ignore the AllowList.

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Docker container locally, and in ECS as a scheduled task.

### OS used

Wofli (container)

### Prowler version

3.5.3

### Pip version

23.1.2

### Context

`"*"` works for the policy matching in the allowlist, which is not desirable because I want to pattern match names

`"run-some-task"` works for the policy matching in the allowlist, which is not desirable due to dynamically generated policy names in some of our aws accounts and the number of entries that would be required

`"run.*-task"` seems to work!  

The docs at https://docs.prowler.cloud/en/latest/tutorials/allowlist/ suggest the `[[:alnum:]]` pattern: `"[[:alnum:]]+-logs" # Will ignore all buckets containing the terms ci-logs, qa-logs, etc. in specified check and regions`, but I'm not able to get it working as expected.
