### ISSUE TITLE
[Bug]: [3.9.0] iam_inline_policy_no_administrative_privileges cannot be ignored by resource

### ISSUE THREAD

**Issue by chbiel** [toniblyx/prowler#2780]
### Steps to Reproduce

```
Allowlist:
  Accounts:
    "*":
      Checks:
        iam_inline_policy_no_administrative_privileges:
          Regions: [ "*" ]
          Resources:
            - abc
            - role/xyz
```

After upgrading to 3.9.0 we get some errors
`Inline policy AwsSSOInlinePolicy for IAM identity ....... allows '*:*' administrative privileges`
but as that is intended, we want to ignore it for some roles.

We have two role, one "normal" role (`role/abc`) and one SSO role (`role/aws-reserved/sso.amazonaws.com/...../.....`).
I tried different variations in the `Resources` list but the FAIL still occoures for both roles.

### Expected behavior

I can ignore `iam_inline_policy_no_administrative_privileges` somehow through the allowlist (I guess based on roles would be the best and easiest option right now).

### Actual Result with Screenshots or Logs

See above.

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

Ubuntu

### Prowler version

3.9.0

### Pip version

22.0.2
