### ISSUE TITLE
Severity level overrides

### ISSUE THREAD

**Issue by ramses999** [toniblyx/prowler#2834]
### New feature motivation

Currently, “Severity” is strictly specified in every check, but our company does not agree with some of them and we want to redefine them.
For example, for the "acm_certificates_expiration_check" check the level is high, but in accordance with internal regulations we have this is the “medium” level (the monitoring team’s fixation metrics depend on this).
Now, as a temporary solution, all prowler outputs are added up “as is”, and only then they are redefined on the SIEM (a simple example in the screenshot can be seen in the MySeverity column).
<img width="1900" alt="image" src="https://github.com/prowler-cloud/prowler/assets/108680000/8f80dba3-5145-4c47-a132-d7f04690eec7">

### Solution Proposed

Add an argument (in addition to "--checks-file") that parses "severity" (if present) and overrides the default value. As a result, it will be possible to specify in one file the list of checks of interest and their new level of criticality.

### Describe alternatives you've considered

-

### Additional context

In mature companies, response time greatly depends on Severity; each organization must determine the level of criticality for itself depending on the assets. The ability to use one input file (in addition to "--checks-file") to specify a list of checks of interest and their new level of criticality will be a great addition.

**Comment by toniblyx** [comment]
Thanks @ramses999 this is something we are considering from long ago. Allowing users to override severity without having to change checks configuration is a valid option, another option we are considering is to adapt severity based on context given by the user or environment (if an account is prod or not, tags with special meaning, etc.) This is for sure helpful, thank you!

**Comment by ramses999** [comment]
@toniblyx  Thanks for the quick response.
In my case, I want to create my own pack (rules + severity). I'm afraid that "severity based on context" may not be flexible enough.
It is better to implement these ideas independently.

**Comment by ramses999** [comment]
Hello Tony (@toniblyx)
When should I wait for an update to redefine criticality?
I want to know about the time frame to make a choice: should I come up with a solution on the side of my dashboard or will it soon appear in the scanner.
What do you think about the example below extending `--list-checks` ? just change the array to an array of tuples

`{
  "aws": [
    ("cloudtrail_log_file_validation_enabled", severity="Medium"),
    ("cloudtrail_multi_region_enabled", severity="Low"),
    ("cloudtrail_logs_s3_bucket_is_not_publicly_accessible", severity="High")
 ]
}`

Or, for example, you can make another parameter `--override-severity FILE` and submit the separate file as input using the example below

`{
  "aws-checks-severity": [
    "cloudtrail_log_file_validation_enabled"="Medium",
    "cloudtrail_multi_region_enabled"="Low",
    "cloudtrail_logs_s3_bucket_is_not_publicly_accessible"="High"
 ]
}`

**Comment by jfagoagas** [comment]
@ramses999 Could this be addressed using the custom checks feature? Because it allows you to create a different / modified metadata files and then run the checks.

https://docs.prowler.cloud/en/latest/tutorials/misc/#custom-checks

**Comment by ramses999** [comment]
@jfagoagas If I need to duplicate all the rules built into Prowler into a separate directory and redefine the criticality in it, and then when calling Prowler specify that it only takes custom checks, then this seems very cumbersome.

**Comment by toniblyx** [comment]
yeah, I agree with @ramses999, to make it easier to customize I think the best way is through configuration. A yaml file that overrides checks metadata would make the trick, that includes severity but also other attributes as well if needed. The approach is similar to what we do for Allow list.

For example, an option like `prowler <provider> --custom-checks-metadata custom_metadata_file.yaml`

And that file like:
```
CustomCheckMetadata:
  Provider:
    "aws":
      Checks:
        "awslambda_function_invoke_api_operations_cloudtrail_logging_enabled":
          Severity:
            - "low"
        "ec2_networkacl_*":
          Severity:
            - "low"
          RelatedUrl:
            - "https://myinternaldocumentation.sample/docs"
    "gcp":
      Checks:
        "serviceusage_cloudasset_inventory_enabled":
          Severity:
            - "critical"
    "azure":
      Checks:
        "defender_ensure_defender_for_dns_is_on":
          Severity:
            - "low"
```

What do you think @jfagoagas ?
