### ISSUE TITLE
[Bug]: Exception merging from "*" and specific account

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#3208]
### Steps to Reproduce

1. prowler aws --config-file prowler/config.yaml -w allowlist.yaml -p iam -f us-east-1 -s iam
2. AWS
3. multi-account

Running prowler for AWS multi-account environment we have common exceptions for some checks (e.g. iam_role_administratoraccess_policy) some roles are expected to have admin privileges in all accounts, and in the specific account, there are some other roles with admin privileges as well. But prowler will use only exceptions from "*" and ignore exceptions from "111111111111" and Role3 will be in the list of findings.
```
Allowlist:
  Accounts:
    "*":
      Checks:
        "iam_role_administratoraccess_policy":
          Regions:
            - "*"
          Resources:
            - "Role1"
            - "Role2"
    "111111111111":
      Checks:
        "iam_role_administratoraccess_policy":
          Regions:
            - "*"
          Resources:
            - "Role3"
```

### Expected behavior

It's expected to merge similar check exceptions from "*" and "specific_account" to get the full list of allowed resources and all roles (Role1, Role2, and Role3) will be ignored during scan.

### Actual Result with Screenshots or Logs

Nothing to add

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

1. EC2 instance
2. Local laptop

### OS used

1. Amazon Linux 2
2. MacOS

### Prowler version

Prowler 3.11.3

### Pip version

pip 22.0.4
