### ISSUE TITLE
[Bug]: cloudwatch_log_group_retention_policy_specific_days_enabled alert on AWS managed log group

### ISSUE THREAD

**Issue by christiandavilakoobin** [toniblyx/prowler#3296]
### Steps to Reproduce

Execute prowler scan with an RDS instance active with enhaced monitoring

### Expected behavior

No alert

### Actual Result with Screenshots or Logs

Prowler detects RDSOSMetrics log group has a 30 days retention policy

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Docker container locally

### OS used

Docker

### Prowler version

3.12.1

### Pip version

The one on docker image

### Context

I am not sure if this is a bug or not, but AWS has a log group called RDSOSMetrics, where it stores information about enhaced monitoring, as you can see here:

https://aws.amazon.com/es/blogs/database/monitor-real-time-amazon-rds-os-metrics-with-flexible-granularity-using-enhanced-monitoring/

This group, by default, has a 30 days retention period. You can manually change it, but as is internal, I think is better not to modify it. In my opinion, this group shouldn't rise an alert.

**Comment by MrCloudSec** [comment]
Hi @christiandavilakoobin, thanks for reaching us out!
For this use case, Prowler has the allowlist feature where you can ignore this type of resources, the syntax would be like:
```
Allowlist:
  Accounts:
    "*":
      Checks:
        "cloudwatch_log_group_retention_policy_specific_days_enabled":
          Regions:
            - "*"
          Resources:
            - "RDSOSMetrics"
```
