### ISSUE TITLE
Cannot mute failed checks based on AWS tags using 4.3.0

### ISSUE THREAD

**Issue by cetteup** [toniblyx/prowler#4597]
### Steps to Reproduce

1. Create tagged AWS resources (tested with EC2 instances, IAM roles)
2. Add tag-based mute list entry matching those resources
3. Run prowler with the mutelist

### Expected behavior

Findings related to the muted checks are reported as muted for the tagged resources.

### Actual Result with Screenshots or Logs

Related findings are not muted, causing prowler to exit with a non-zero exit code. Additionally, no findings are muted for checks in the mutelist containing both specific resources as well as tags. Meaning not only do tag-based mutelist entries not work, they seem to break the entire mutelist entry for the relevant check.

Note: When the mutelist contains an empty array of tags for a check, the resource-based exclusions still work. Adding an empty string value also has no negative impact. But even adding one of the examples (`environment=dev`) breaks the resource-based muting.

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation/GitHub Actions

### OS used

`ubuntu-latest` (GitHub Actions)/Fedora 40 Workstation

### Prowler version

4.3.0

### Pip version

24.2

### Context

No warnings/errors are logged regarding our mutelist. When reverting back to 4.2.4, all findings are muted as expected using the exact same mutelist.

I could not find any obvious (to me) reason for the tags breaking while quickly looking through the mutelist code. My best guess is that this issue was somehow introduced by #4413 (just looking for changes to the mutelist added with 4.3.0).

**Comment by MrCloudSec** [comment]
Hi @cetteup, thanks for reaching us out!
Please, could you send us your mutelist so we can do a further investigation on what is happening?

**Comment by cetteup** [comment]
I was able to reproduce this with a super simple mutelist:
```yaml
Mutelist:
  Accounts:
    '*':
        ec2_instance_detailed_monitoring_enabled:
          Regions: ['*']
          Resources: ['*']
          Tags:
            - 'Name=Database/AdminInstance'
```

I just noticed that the tags "breaking" resource-based entries might be a misunderstanding on my part. Just to clarify: Are the different mutelist options applied as AND or as OR? If it's AND then of course the failed checks in the under `Resources` don't get muted if those resources don't also have the relevant tag.

**Comment by cetteup** [comment]
One more (potentially) important piece of information: I do see the exact tag from the mutelist in the `RESOURCE_TAGS` column of the findings, so it both exists and is detected by prowler (along with all the other tags on that instance).

**Comment by MrCloudSec** [comment]
Thanks for the information @cetteup !

We have identified the issue and working now on a fix.

About your question, the mutelist acts as an OR.

**Comment by thomscode** [comment]
For me this appears to work as long as the tags do not contain a forward slash `/`.

This works:
```yaml
Mutelist:
  Accounts:
    "*":
      Checks:
        "some_check_name":
          Regions: ["*"]
          Resources: ["*"]
          Tags:
            - "aws:eks:cluster-name=dev"
```
But this doesn't:
```yaml
Mutelist:
  Accounts:
    "*":
      Checks:
        "some_check_name":
          Regions: ["*"]
          Resources: ["*"]
          Tags:
            - "'karpenter.sh/managed-by'=dev"
```

**Comment by cetteup** [comment]
I quickly retested this with some simpler tags (and a working mutelist, the above example was missing the `Checks` key, which did not raise any errors but also did nothing). As soon as I add *any* tag, the check is not muted anymore - even if I specifically mention the affected resource under `Resources`. Happens for me even with tags as simple as `thekey=thevalue`.
```yaml
Mutelist:
  Accounts:
    '*':
      Checks:
        ec2_instance_detailed_monitoring_enabled:
          Regions: ['*']
          Resources: ['*']
          Tags:
            - 'thekey=thevalue'
```
When I `grep` through the output CSV with the same tag, I get a match.

**Comment by jfagoagas** [comment]
> I quickly retested this with some simpler tags (and a working mutelist, the above example was missing the `Checks` key, which did not raise any errors but also did nothing). As soon as I add _any_ tag, the check is not muted anymore - even if I specifically mention the affected resource under `Resources`. Happens for me even with tags as simple as `thekey=thevalue`.
> 
> ```yaml
> Mutelist:
>   Accounts:
>     '*':
>       Checks:
>         ec2_instance_detailed_monitoring_enabled:
>           Regions: ['*']
>           Resources: ['*']
>           Tags:
>             - 'thekey=thevalue'
> ```
> 
> When I `grep` through the output CSV with the same tag, I get a match.

Hello @cetteup, this is strange because the above Mutelist works in our test environments 🤔 It'd be great if we can have also the resource tags.

Could you be able to jump into a quick call to review it? You can join our Prowler Slack using this invite link https://join.slack.com/t/prowler-workspace/shared_invite/zt-2luugg3ld-_MlE692tRwAZoMMrZ1sV7w

**Comment by jfagoagas** [comment]
@thomscode could you share with us the Mutelist you are using and the tags present in your resource because we are not being able to reproduce this issue.

**Comment by cetteup** [comment]
After a brief chat with @jfagoagas, I set up a fresh EC2 instance and started gradually adding tags. With an interesting finding: Muting works with whatever tag is shown first in the tag list of the AWS web console. Meaning it works by default with a single tag, but stops working as soon as you have more than one tag and are not using the first one. Also verified with our existing EC2 instances. Tag we actually want to use is 7th in the list. If I use the first listed tag instead, muting works.

**Comment by jfagoagas** [comment]
That's exactly what I saw in some tests I did 🤔 Let me add some unit tests and see ...

**Comment by jfagoagas** [comment]
@cetteup @thomscode could you please run Prowler again with the code in the above PR? The branch name is `PRWLR-4383-cannot-mute-failed-checks-based-on-aws-tags-using-4-3-0-fix`.

Thanks in advance!

**Comment by cetteup** [comment]
Version on the branch works with non-first tags, including ones with special characters (e.g. the initial `Name=Database/AdminInstance`). Nice work! 🚀

Only "issue" that remains (which may not be unrelated/a misunderstanding): When I try to mute both a specific resource by *and* another one by a tag for the same check, findings for neither end up being muted. If `Resources` and `Tags` are really OR-linked, I believe I should be able to do something like
```yaml
Mutelist:
  Accounts:
    '*':
      Checks:
        ec2_instance_detailed_monitoring_enabled:
          Regions: ['*']
          Resources:
            - 'i-123456789' # Mute specific resource by name
          Tags:
            - 'Name=Database/AdminInstance' # AND mute other resource by tag
```

**Comment by jfagoagas** [comment]
Thank you for testing it!!

Regarding the mutelist logic, as far as I know, at least is coded in that way, the fields are AND-linked, e.g.:
With the following Mutelist:
```yaml
Mutelist:
  Accounts:
    '*':
      Checks:
        ec2_instance_detailed_monitoring_enabled:
          Regions: ['*']
          Resources:
            - 'i-123456789' # Mute specific resource by name
          Tags:
            - 'Name=Database/AdminInstance' # AND mute other resource by tag
```
- Resource: `i-123456789` without tags -> **NOT MUTED**
- Resource: `i-123456789` with tag `'Name=Database/AdminInstance'` -> **MUTED**
- Resource: `i-00000000` with tag `'Name=Database/AdminInstance'` -> **NOT MUTED**

**Comment by cetteup** [comment]
Thanks for clarifying and documenting it. Issue is good to be closed now when merging the PR.

Is there any other way of achieving the above-described kind of OR-ed muting? We have some CDK-created resources which are simply called `default` but have more specific tags. However, we need to mute the same check for resources without any usable tags (but distinct names).

**Comment by thomscode** [comment]
@jfagoagas,
Sorry for being late to reply. I confirmed that the tag that works is listed first when querying for tags using the AWS CLI. I also confirmed, since the PR fixing this was merged, that the `master` branch does fix the issue I'm having.

Thank you for getting this done quickly, I'm looking forward to seeing this released.

**Comment by jfagoagas** [comment]
Hello @cetteup , could you please share with me some examples to help you craft a valid Mutelist for your use case?

Something like the following:
- Account/s
- Check/s
- Resource/s and their tag/s

**Comment by thomscode** [comment]
@jfagoagas,

Below is what is working now. As Karpenter adds and removes nodes I'm having to add new tags each instance will have a different first tag.
```
Mutelist:
  Accounts:
    "....":
      Checks:
        "ec2_instance_secrets_user_data":
          Regions:
            - "us-west-2"
          Resources:
            - "*"
          Tags:
            - "karpenter.sh/managed-by=dev"
            - "aws:eks:cluster-name=dev"
            - "karpenter.sh/nodepool=default"
            - "karpenter.sh/nodepool=medium"
            - "karpenter.sh/nodepool=4xlarge"
            - "karpenter.k8s.aws/ec2nodeclass=default"
            - "karpenter.k8s.aws/ec2nodeclass=medium"
            - "karpenter.k8s.aws/ec2nodeclass=4xlarge"
            - "kubernetes.io/cluster/dev=owned"
```
