### ISSUE TITLE
Conflicting documentation for mutelist tags on AWS

### ISSUE THREAD

**Issue by dlouzan** [toniblyx/prowler#4782]
### Steps to Reproduce

The mutelist tags specification on AWS appears to be applied as an OR of the tags. This is consistent with the documentation at <https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/mutelist/#how-the-mutelist-works>:

> The Mutelist uses an "ANDed" and "ORed" logic to determine which resources, checks, regions, and tags should be muted. For each check, the Mutelist checks if the account, region, and resource match the specified criteria, using an "ANDed" logic. If tags are specified, the mutelist uses and "ORed" logic to see if at least one tag is present in the resource.

But then below on the yaml example:

```yaml
### Tags is an optional list that matches on tuples of 'key=value' and are "ANDed" together.
### Use an alternation Regex to match one of multiple tags with "ORed" logic.
### For each check you can except Accounts, Regions, Resources and/or Tags.
```

And then proceeds to use an example where it assumes an AND:

```yaml
Mutelist:
  Accounts:
    "123456789012":
        ...
        "*":
          Regions:
            - "*"
          Resources:
            - "test"
          Tags:
            - "test=test"         # Will mute every resource containing the string "test" and the tags 'test=test' and
            - "project=test|project=stage" # either of ('project=test' OR project=stage) in account 123456789012 and every region
```

In my tests with the latest version 4.3.3, passing a tag multiple times with different values is applying an OR, as I expect, e.g.:

```yaml
# Mutes anything with a `Type=type1`, or with `Name=host1`
Tags:
  - "Type=type1"
  - "Name=host1"
```

A related question in this case is: what is the syntax for applying an AND of tags? Exactly like the yaml example in the documentation.

### Expected behavior

Consistent documentation

### Actual Result with Screenshots or Logs

See <https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/mutelist/#how-the-mutelist-works>

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Docker container and pip install locally

### OS used

macOS and Amazon Linux 2023

### Prowler version

4.3.3

### Pip version

23.2.1
