### ISSUE TITLE
Improve the AWS Mutelist including the `cloudformation_stack_outputs_find_secrets` for `StackSet-AWSControlTower*`

### ISSUE THREAD

**Issue by jfagoagas** [toniblyx/prowler#4894]
### Steps to Reproduce

`detect-secrets` is flagging some CloudFormation Outputs, generated from AWS Control Tower, as secrets. Even being some possible secret value a user can not modify Control Tower resources not to break the service setup and configuration.

### Expected behavior

We need to add the following block to the [AWS Default Mutelist](https://github.com/prowler-cloud/prowler/blob/master/prowler/config/aws_mutelist.yaml) in order to mute the results generated from the `cloudformation_stack_outputs_find_secrets` affecting AWSControl Tower resources.

```yaml
cloudformation_stack_outputs_find_secrets:
          Regions:
          - "*"
          Resources:
          - StackSet-AWSControlTower*
```

### Actual Result with Screenshots or Logs

N/A

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

N/A

### OS used

N/A

### Prowler version

4.3.5

### Pip version

24
