### ISSUE TITLE
Kubernetes KubeConfig ConfigException[214]: Service host/port is not set.

### ISSUE THREAD

**Issue by mirisbowring** [toniblyx/prowler#5489]
### Steps to Reproduce

For testing the kubernetes provider, i've setup a Kubernetes on a MacBook and exposed it to the local network.
I am trying to scan the cluster from a different linux based device.

I am able to execute `kubectl --kubeconfig kube.conf get pods` to test cluster access and permissions.

Now, if i execute: `docker run --rm toniblyx/prowler:stable kubernetes --kubeconfig-file $pwd/kube.conf` I get the following error: `CRITICAL: ConfigException[214]: Service host/port is not set.`

### Expected behavior

I would expect the scan to execute since connection to the cluster is obviously possible.

### Actual Result with Screenshots or Logs

```
2024-10-21 14:52:35,277 [File: provider.py:228] 	[Module: provider]	 CRITICAL: ConfigException[214]: Service host/port is not set.
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v4.4.1
|_| the handy multi-cloud security tool

Date: 2024-10-21 14:52:34
```

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Prowler is being executed as docker command from an linux host on the same local network

Kubernetes is exposed to the local network via: `kubectl proxy --address='0.0.0.0' --port=8080 --disable-filter=true` (This is just for testing)

### OS used

MacOS and Linux

### Prowler version

4.4.1

### Pip version

the one bundled in the latest stable docker image

### Context
This is the working `kube.config`

```yaml
apiVersion: v1
clusters:
- cluster:
    server: http://10.100.3.38:8080
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: prowler-service-acc
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlhBMHBI...
```
