### ISSUE TITLE
Build prowler container images for arm64 architecture as well

### ISSUE THREAD

**Issue by ctrlaltdev** [toniblyx/prowler#6689]
### New feature motivation

Prowler container images are only available for amd64:
- https://hub.docker.com/r/prowlercloud/prowler-api/tags
- https://hub.docker.com/r/prowlercloud/prowler-ui/tags
- https://hub.docker.com/r/prowlercloud/prowler/tags

Meaning that it cannot run on machines like recent Apple devices or AWS Graviton instances.

### Solution Proposed

Update the workflows that build the image to leverage QEMU, as documented here: https://docs.docker.com/build/ci/github-actions/multi-platform/

```
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image and Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          
```

### Describe alternatives you've considered

N/A
