### ISSUE TITLE
Unable to mute all resources based on resource name OR tags

### ISSUE THREAD

**Issue by KieranP** [toniblyx/prowler#7079]
Currently cannot mute all resources based on resource name OR tags.

Current mutelist functionality only supports resource name AND tags.

This only works when resource AND tags are true:

```yml
Mutelist:
  Accounts:
    '*':
      Checks:
        '*':
          Regions:
            - '*'
          Resources:
            - '*bucketav*'
          Tags:
            - 'Name=*bucketav*'
```

I need a solution to mute if resource OR tags are true.

Providing multiple checks with same name doesn't work:

```yml
Mutelist:
  Accounts:
    '*':
      Checks:
        '*':
          Regions:
            - '*'
          Resources:
            - '*bucketav*'
        '*':
          Regions:
            - '*'
          Resources:
            - '*'
          Tags:
            - 'Name=*bucketav*'
```

The above only takes into account the second, i.e. it overrides.

There does not appear to be any way to accomplish this currently?
