### ISSUE TITLE
Sturggled to install Prowler App on Arm64 - providing notes for others to reference on workaround

### ISSUE THREAD

**Issue by Fennerr** [toniblyx/prowler#7659]
### Steps to Reproduce

Tried to setup the prowler app on an arm64 architecture, and struggled with following the instructions (well they gave me errors when trying to follow them). I also am using docker-compose instead of the newer docker compose, but I thought I would just give some of my notes on how I got it running. I did follow the instructions in the wiki on setting that linux/arm64 value in the .env file.

Git clone the repo
cd in ui, build the image:
* docker buildx build --platform linux/arm64 -t prowler-ui --load .

cd into api, build the image:
* docker buildx build --platform linux/arm64 -t prowler-api --load .

From previous attempts, I had a platform incompatible image of postgresql. Had to pull it manually for the correct platform:
* docker pull --platform linux/arm64 postgres:16.3-alpine3.20

I did the same for valkey when debugging the issue, as it was throwing the same issue (see screenshot further down with exec format error):
* docker pull --platformvalkey/valkey:7-alpine3.19

Then modify the docker-compose.yaml file in the root directory to rather use the local images:

```
services:
  api:
    hostname: "prowler-api"
    image: prowler-api
    env_file:
      - .env
    ports:
      - "${DJANGO_PORT:-8080}:${DJANGO_PORT:-8080}"
    volumes:
      - "/tmp/prowler_api_output:/tmp/prowler_api_output"
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    entrypoint:
      - "/home/prowler/docker-entrypoint.sh"
      - "prod"

  ui:
    image: prowler-ui
    env_file:
      - .env
    ports:
      - ${UI_PORT:-3000}:${UI_PORT:-3000}

  postgres:
    image: postgres:16.3-alpine3.20
    hostname: "postgres-db"
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_ADMIN_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:7-alpine3.19
    hostname: "valkey"
    volumes:
      - ./_data/valkey:/data
    env_file:
      - .env
    ports:
      - "${VALKEY_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'valkey-cli ping'"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker:
    image: prowler-api
    env_file:
      - .env
    volumes:
      - "/tmp/prowler_api_output:/tmp/prowler_api_output"
    depends_on:
      valkey:
        condition: service_healthy
      postgres:
        condition: service_healthy
    entrypoint:
      - "/home/prowler/docker-entrypoint.sh"
      - "worker"

  worker-beat:
    image: prowler-api
    env_file:
      - ./.env
    depends_on:
      valkey:
        condition: service_healthy
      postgres:
        condition: service_healthy
    entrypoint:
      - "../docker-entrypoint.sh"
      - "beat"
```

And then run docker-compose up

### Expected behavior

Prehaps have arm64 images prebuilt. Im a noob at docker though - not sure if this is correct, but seems like it might help solve the issue.

### Actual Result with Screenshots or Logs

Issue shown when trying to do a docker-compose up

![Image](https://github.com/user-attachments/assets/d06c87ff-a69d-43fb-a572-deb93d44ec30)

Indications that it is an architecture issue:

![Image](https://github.com/user-attachments/assets/3a7554f1-15df-4704-b25e-5086883ab946)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

CLI

### OS used

Kali linux arm64

### Prowler version

3.11.3 (doesnt matter, this is a docker setup issue, didnt use the cli)

### Pip version

same as above

**Comment by MrCloudSec** [comment]
Hi @Fennerr, thanks for opening this issue. We will review it internally and let you know asap!

**Comment by jfagoagas** [comment]
Hello @Fennerr, how are you doing? It's been a minute since the last time we've talked.

The issue you're facing is because the Prowler App needs to be built for `amd64` so you must use `--platform linux/amd64` instead. We did not have time to explore the way to build our containers for `arm` _yet_.

I have a question about something you said ` did follow the instructions in the wiki on setting that linux/arm64 value in the .env file.` which wiki are you referring to?

Please let me know if the above fixes the issue and allows you to use Prowler.

Thanks!

**Comment by smd-stevehuynh** [comment]
Hi there,
I already run successful on EC2 arm t4g.medium.
With defined platform inside the docker-compose.yml
```
services:
  api:
    hostname: "prowler-api"
    image: prowlercloud/prowler-api:${PROWLER_API_VERSION:-stable}
    platform: linux/amd64
  ui:
    image: prowlercloud/prowler-ui:${PROWLER_UI_VERSION:-stable}
    platform: linux/amd64
  postgres:
    image: postgres:16.3-alpine3.20
    platform: linux/arm64
  valkey:
    image: valkey/valkey:7.2-alpine3.19
    platform: linux/arm64
  worker:
    image: prowlercloud/prowler-api:${PROWLER_API_VERSION:-stable}
    platform: linux/amd64
  worker-beat:
    image: prowlercloud/prowler-api:${PROWLER_API_VERSION:-stable}
    platform: linux/amd64
```
Ok for `docker-compose up`
![Image](https://github.com/user-attachments/assets/5d718843-a7dd-4215-a5fb-a7d8e905c5a0)

But the API and Worker container has failed with unknown reason:
here is the logs:

```
#docker logs prowler-api-1
Applying database migrations...

Command '['/usr/local/bin/python', '-EsSc', 'import platform; print(platform.python_version())']' timed out after 5.0 seconds
Managing DB partitions...

Command '['/usr/local/bin/python', '-EsSc', 'import platform; print(platform.python_version())']' timed out after 5.0 seconds
Starting the Gunicorn server...

Command '['/usr/local/bin/python', '-EsSc', 'import platform; print(platform.python_version())']' timed out after 5.0 seconds
```

```
docker logs prowler-worker-1
Starting the worker...

Command '['/usr/local/bin/python', '-EsSc', 'import platform; print(platform.python_version())']' timed out after 5.0 seconds
```

Is there any things else I missed?
