### ISSUE TITLE
CloudWatch Metric Checks failing when alarms are present.

### ISSUE THREAD

**Issue by tradichel** [toniblyx/prowler#960]
Have a client who's failing CloudWatch metric checks but has alarms in place. Other CloudWatch metrics checks are failing as well and I've had this same issue working with other clients. They also told me Nessus produces the same findings.

For example #3.3:
https://github.com/toniblyx/prowler/blob/master/checks/check33
check3x '\$\.userIdentity\.type\s*=\s*"Root".+\$\.userIdentity\.invokedBy NOT EXISTS.+\$\.eventType\s*!=\s*"AwsServiceEvent"'

Error says no metrics found for CloudTrail/DefaultLogGroup.

The client is using the template below.  Why is this check failing when the metrics exist in their account and appear to be correct (or am I missing something)? 

```
  CloudTrailLogGroupName:
    Type: String
    Default: CloudTrail/DefaultLogGroup

RootAccountUsage:
    Type: 'AWS::Logs::MetricFilter'
    Properties:
      LogGroupName: !Ref CloudTrailLogGroupName
      FilterPattern: >-
        { $.userIdentity.type = "Root" && $.userIdentity.invokedBy NOT EXISTS && $.eventType != "AwsServiceEvent" }
      MetricTransformations:
        - MetricNamespace: CloudTrailMetrics
          MetricName: RootAccountUsage
          MetricValue: '1'
  RootAcccountUsageAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: RootAccountUsage
      AlarmDescription: Alarm when activity is found by the root account
      AlarmActions:
        - !ImportValue SNSCyberSecurity
      MetricName: RootAccountUsage
      Namespace: CloudTrailMetrics
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: '1'
      Period: '300'
      Statistic: Sum
      Threshold: '1'
```
